### ISSUE TITLE
Support for DNG 1.5

### ISSUE THREAD

**Issue by clanmills** [Exiv2/exiv2#1397]
The latest version of the DNG Specification is 1.5 and available here:  https://wwwimages2.adobe.com/content/dam/acom/en/products/photoshop/pdfs/dng_spec_1.5.0.0.pdf
 
Exiv2 supports DNG 1.3 tags on branch 0.27-maintenance thanks to work by @kmilos on #1392

**Comment by kmilos** [comment]
Below is a list of outstanding items to help with tracking this.

*  DNG <=1.3 support completion

- [x] Extensions to existing TIFF tags (#1392)
- [ ] Parsing of Camera Profile IFDs

*  DNG 1.4 support

- [x] Extensions to existing TIFF tags (#1391)
- [ ] Additional tags (#1161 WIP)

0xc791 OriginalDefaultFinalSize
0xc792 OriginalBestQualityFinalSize
0xc793 OriginalDefaultCropSize
0xc7a3 ProfileHueSatMapEncoding (+ translated values)
0xc7a4 ProfileLookTableEncoding (+ translated values)
0xc7a5 BaselineExposureOffset
0xc7a6 DefaultBlackRender (+ translated values)
0xc7a7 NewRawImageDigest
0xc7a8 RawToPreviewGain
0xc7b5 DefaultUserCrop

* DNG 1.5 support

- [x] Extensions to existing TIFF tags (#1391)
- [ ] Additional tags

0xc7e9 DepthFormat (+ translated values)
0xc7ea DepthNear
0xc7eb DepthFar
0xc7ec DepthUnits (+ translated values)
0xc7ed DepthMeasureType (+ translated values)
0xc7ee EnhanceParams
